# Generated by Django 5.0.3 on 2024-05-19 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XinvestApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='proof_of_payment',
            field=models.ImageField(blank=True, null=True, upload_to='proof_of_payments/'),
        ),
    ]
